CREATE TABLE public.solar_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    solar_irradiance DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION,
    panel_angle DOUBLE PRECISION,
    energy_output DOUBLE PRECISION,
    energy_output_class TEXT
);